In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,4,76,888,0])
arr
type(arr)

numpy.ndarray

In [5]:
a = [22,7,56,9]
a
type(a)

list

In [6]:
b = (22,72,56,91)
print(b) 
type(b)

(22, 72, 56, 91)


tuple

In [7]:
c = {22,7,56,1,49}
print(c) 
type(c) 

{1, 49, 22, 7, 56}


set

In [8]:
ab = [22,7,56,9, "hello" , 3.5]
print(ab) 
type(ab) 

[22, 7, 56, 9, 'hello', 3.5]


list

In [9]:
np.array(ab)

array(['22', '7', '56', '9', 'hello', '3.5'], dtype='<U32')

In [10]:
#dtype='<U32' means that all the datatypes are converted in string because array does not support multiple data type , its support same data typ only

In [11]:
abc = [22,7,56,9 , 3.5]
print(abc) 
type(abc)

[22, 7, 56, 9, 3.5]


list

In [12]:
np.array(abc)

array([22. ,  7. , 56. ,  9. ,  3.5])

In [13]:
#dtype='<U32' means that all the datatypes are converted in float because array does not support multiple data type , its support same data typ only

In [14]:
l= [[1,2,3], [4,5,6], [7,8,9]]
print(l)
type(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [15]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr =np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [17]:
np.random.rand(10)

array([0.25728954, 0.98489293, 0.1058088 , 0.41056963, 0.14200538,
       0.59527303, 0.8574179 , 0.68692404, 0.730918  , 0.32549593])

In [18]:
np.random.randn(10)

array([-0.52921608, -0.22430961, -1.79096849, -0.44398229, -0.5987711 ,
       -1.19819461, -0.24737081, -1.0913194 ,  1.16424422,  0.4530878 ])

In [20]:
np.random.randint(10)

7

In [24]:
arr = np.array([[1,4,6],[56,7,1],[5,7,80]])
arr

array([[ 1,  4,  6],
       [56,  7,  1],
       [ 5,  7, 80]])

In [25]:
arr.size

9

In [27]:
arr.shape

(3, 3)

In [29]:
arr.dtype

dtype('int64')

TypeError: 'numpy.ndarray' object is not callable