In [298]:
import numpy as np

In [299]:
a1 = np.array([1,4,7,44])
a2 = np.array([5,76,10,44])

In [300]:
a1+a2

array([ 6, 80, 17, 88])

In [301]:
a1-a2

array([ -4, -72,  -3,   0])

In [302]:
a1*a2

array([   5,  304,   70, 1936])

In [303]:
a1**a2

array([        1,         0, 282475249,         0])

In [304]:
a1/a2

array([0.2       , 0.05263158, 0.7       , 1.        ])

In [305]:
a1//a2

array([0, 0, 0, 1])

In [306]:
a1%a2

array([1, 4, 7, 0])

## broadcasting

In [307]:
l= [10,15,20,55,25,68]
arr= np.array(l)

In [308]:
arr+10

array([20, 25, 30, 65, 35, 78])

In [309]:
arr2 = np.arange(1,31).reshape(5,6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [310]:
arr2+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40]])

In [311]:
a= np.arange(1,21)
a
#output will be in vector form

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [312]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [313]:
slice = a[:20]
slice = slice*10
slice

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [314]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [315]:
slice = a[2:6]
slice

array([3, 4, 5, 6])

In [316]:
a
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [317]:
b[0] = 9
b

array([ 9,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [318]:
a

array([ 9,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [319]:
a
b= a.copy()
b

array([ 9,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [320]:
b[0] = 10
b

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [321]:
a

array([ 9,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## MATRIX OPERATION

In [322]:
A = np.array([[2,4],[5,11]])
B = np.array([[0,1],[6,10]])
#This is in matrix

In [323]:
A

array([[ 2,  4],
       [ 5, 11]])

In [324]:
B

array([[ 0,  1],
       [ 6, 10]])

In [325]:
A @ B
#matrix multiplication

array([[ 24,  42],
       [ 66, 115]])

In [326]:
np.dot(A,B)

array([[ 24,  42],
       [ 66, 115]])

## ADVANCE MATRIX MANIPULATION

## STACKING  ARRAY

In [327]:
a = np.array([2,5,11])
b = np.array([1,16,10])
#This is in vector 

In [328]:
a

array([ 2,  5, 11])

In [329]:
b

array([ 1, 16, 10])

In [330]:
np.vstack((a,b))
#vertically

array([[ 2,  5, 11],
       [ 1, 16, 10]])

In [331]:
np.hstack((a,b))
#horizontally

array([ 2,  5, 11,  1, 16, 10])

In [332]:
np.column_stack((a,b))

array([[ 2,  1],
       [ 5, 16],
       [11, 10]])

In [333]:
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [337]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [338]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [339]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [340]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [344]:
for i in c:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
