In [1]:
import numpy as np

In [2]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr_slice = arr[3::2]
arr_slice

array([5, 7, 9])

In [4]:
arr[3]

np.int64(5)

In [5]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [6]:
arr[4]

array([21, 22, 23, 24, 25])

In [7]:
arr[5]

array([26, 27, 28, 29, 30])

In [8]:
arr[0,0]

np.int64(1)

In [9]:
arr[0,2]

np.int64(3)

In [10]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [11]:
arr[0:,0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[1:2,0:]

array([[ 6,  7,  8,  9, 10]])

In [13]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[1]   #its printing rows

array([ 6,  7,  8,  9, 10])

In [15]:
arr[4]

array([21, 22, 23, 24, 25])

In [16]:
arr[1,2]

np.int64(8)

In [17]:
arr[0,0]

np.int64(1)

In [19]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [20]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
bool_index = arr %2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [24]:
arr= arr[bool_index]
arr

array([12, 14, 16, 18, 20])